- name: Environment Setup
  hosts: localhost
  become: true
  tasks:

    - name: Identifica usuario
      command: whoami
      register: executing_user

    - name: Package repository update
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - python3-dev
        - python3-venv
        - libssl-dev
        - libffi-dev
        - build-essential
        - software-properties-common

    - name: Docker install
      shell: curl -sSL https://get.docker.com | sh

    - name: Add user to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes
