---
version: "3"

services:

  # https://hub.docker.com/_/influxdb/
  influxdb:
    image: influxdb:2.7.3-alpine
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
      - 2003:2003
    networks:
      - influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME='username'
      - DOCKER_INFLUXDB_INIT_PASSWORD='password'
      - DOCKER_INFLUXDB_INIT_ORG='Organization'
      - DOCKER_INFLUXDB_INIT_BUCKET='DefaultBucket'
      - INFLUXDB_GRAPHITE_ENABLED=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/influxdb2:/etc/influxdb2
      - influxdb2-storage:/var/lib/influxdb2
    restart: unless-stopped

  # https://hub.docker.com/_/telegraf
  telegraf:
    image: telegraf:1.28.3-alpine
    container_name: telegraf
    hostname: telegraf
    depends_on:
      - influxdb
    ports:
      - 8125:8125
    networks:
      - influxdb
    environment:
      INFLUX_TOKEN: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/telegraf:/etc/telegraf
    restart: unless-stopped

  # https://hub.docker.com/_/chronograf
  chronograf:
    image: chronograf:1.10.2-alpine
    container_name: chronograf
    hostname: chronograf
    depends_on:
      - influxdb
      - kapacitor
      - telegraf
    ports:
      - 8888:8888
    networks:
      - influxdb
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - chronograf-storage:/var/lib/chronograf
    restart: unless-stopped

  # https://hub.docker.com/_/kapacitor
  kapacitor:
    image: kapacitor:1.7.1-alpine
    container_name: kapacitor
    hostname: kapacitor
    ports:
      - 9092:9092
    networks:
      - influxdb
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - kapacitor-storage:/var/lib/kapacitor
    restart: unless-stopped

volumes:
  influxdb2-storage:
  chronograf-storage:
  kapacitor-storage:

networks:
  influxdb:
    name: influxdb
    driver: bridge
