---
version: "3.8"

services:
  grafana:
    image: grafana/grafana:10.0.1
    hostname: grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-storage:
