---
version: '3.3'

services:
    speedtest:
        image: openspeedtest/latest:v2.0.5
        hostname: openspeedtest
        container_name: openspeedtest
        ports:
            - '4000:3000'
            - '4001:3001'
        restart: unless-stopped

